### PR TITLE
Overhauled macOS Application

### PR DESCRIPTION
**Pull request by dosdude1**
- **Added support for Mac OS X 10.9 Mavericks and later**
- Fixed window resizing/scaling
- Fixed misspelling
- Used real font
- Removed unused menu bar items
- Added .gitignore for macOS junk

### CODE REVIEW

**Comment by LogoiLab** [comment]
Thank lord someone fixed this garbage application.

**Comment by chris-short** [comment]
Thank you for doing this work @dosdude1. Now if I could only compile this and use it.

**Comment by dosdude1** [comment]
> Thank you for doing this work @dosdude1. Now if I could only compile this and use it.

Make sure you're using a later version of Xcode (I was using Xcode 11). Also the compiled binary is located in the repo, "SvgConverter_v0-1_app.zip" in the "gui-macos" directory.

**Comment by jtrentadams** [comment]
@dosdude1 - Thanks for your work on this! Apologies it took me so long to merge your branch into the master. The cat who developed the code has long since fallen off the map, and I appreciate your help.  Hit me up if I can buy you a beverage of your choice (or toss you an autographed photo from "Star Wars: The Force Awakens"). Cheers!

**Comment by ghost** [comment]
> - **Added support for Mac OS X 10.9 Mavericks and later**
> 
> - Fixed window resizing/scaling
> 
> - Fixed misspelling
> 
> - Used real font
> 
> - Removed unused menu bar items
> 
> - Added .gitignore for macOS junk

**Pull request merged**
